#!/usr/bin/env bash
#
# virtual_env_segment - the active Python virtualenv.

[[ -z ${PL_SYMBOLS[python]} ]] && PL_SYMBOLS[python]='py'  # Python, plain text

#######################################
# Appends the active virtualenv's name.
# Globals:
#   VIRTUAL_ENV, PL_SYMBOLS
# Arguments:
#   $1: background colour name.
#   $2: foreground colour name.
#######################################
virtual_env_segment() {
  [[ -z ${VIRTUAL_ENV} ]] && return 0
  pl_add_segment "$1" "$2" " ${PL_SYMBOLS[python]} ${VIRTUAL_ENV##*/} "
}
